name: example

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3
      with:
      # Required - kibot config file
        config: /opt/kibot/config/bundle/documentation.default.kibot.lst
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
      # optional - verbose output info
        verbose: 1
    - uses: nerdyscout/kicad-exports@v2.3
      with:
      # Required - kibot config file
        config: /opt/kibot/config/bundle/fabrication.jlcpcb.kibot.lst
      # optional - prefix to output defined in config
        dir: fab
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
      # optional - verbose output info
        verbose: 1
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: fab
        path: fab